name: benchmark

on: workflow_dispatch

permissions: read-all
env:
  GO_VERSION: "~1.24.0"
  
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: "**/go.sum"
      - name: Run benchmarks
        run: go test -run=^$ -bench=. -benchmem ./...
            
