name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all
env:
  GO_VERSION: "~1.24.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Revive
        uses: docker://ghcr.io/morphy2k/revive-action:v2
        with:
          config: revive.toml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: "**/go.sum"
      - name: Run tests
        run: go test -coverprofile=coverage.txt ./...
      - name: Upload coverage report
        uses: codecov/codecov-action@v5.4.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage.txt
          verbose: true
        
